services:
  MudBlazor-Frontend:
    image: ${DOCKER_REGISTRY-}dlsmandatoryproject
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/DLS_Mandatory_Project/Dockerfile
    networks:
      - chatnet
  
      
  RabbitMQ:
    image: rabbitmq:4.0-management    


  chatservice:
    image: ${DOCKER_REGISTRY-}chatservice
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/ChatService/Dockerfile
    depends_on:
      - Redis-Backplane
    networks:
      - chatnet
    deploy:
          replicas: 2
    

  nginx-loadbalancer:
    image: nginx:latest    
    depends_on:
      - chatservice
    networks:
      - chatnet


  Redis-Backplane:
    image: redis:latest
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge