services:
  MudBlazor-Frontend:
    image: ${DOCKER_REGISTRY-}dlsmandatoryproject
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/DLS_Mandatory_Project/Dockerfile
  RabbitMQ:
    image: rabbitmq:4.0-management    

