services:
  MudBlazor-Frontend:
    image: ${DOCKER_REGISTRY-}dlsmandatoryproject
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/DLS_Mandatory_Project/Dockerfile

  filetransferservice:
    image: ${DOCKER_REGISTRY-}filetransferservice
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/FileTransferService/Dockerfile
  
  RabbitMQ:
    image: rabbitmq:3.12-management

  postgres:
    image: postgres:17.4
    container_name: postgres_user_service_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data

