services:
  MudBlazor-Frontend:
    image: ${DOCKER_REGISTRY-}dlsmandatoryproject
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/DLS_Mandatory_Project/Dockerfile

  filetransferservice:
    image: ${DOCKER_REGISTRY-}filetransferservice
    build:
      context: .
      dockerfile: DLS_Mandatory_Project/FileTransferService/Dockerfile

