apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: ClusterIP # Changed from NodePort to ClusterIP
  selector:
    app: apigateway
  ports:
  - name: http
    protocol: TCP
    port: 8086 # External port for HTTP (used by Ingress)
    targetPort: 8080 # Internal container port (application listening port)