apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
  - name: http
    protocol: TCP
    port: 8086 #8086       # External port for HTTP
    targetPort: 8080 # Internal container port (application listening port)
    nodePort: 30086 #30086  # Optional: Specify a custom NodePort