apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: ClusterIP #NodePort
  selector:
    app: userservice
  ports:
  - name: http
    protocol: TCP
    port: 8082 #8086       # External port for HTTP
    targetPort: 8080 # Internal container port (application listening port)
    # nodePort: 30082 #30086  # Optional: Specify a custom NodePort