apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  - protocol: TCP
    port: 8083
    targetPort: 8083