apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: ClusterIP # Changed from NodePort to ClusterIP
  selector:
    app: userservice
  ports:
  - name: http
    protocol: TCP
    port: 8082 # External port for HTTP
    targetPort: 8080 # Internal container port (application listening port)