server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Integration with Grafana Loki:
clients:
  - url: http://loki:3100/loki/api/v1/push # URL of Loki server

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: varlogs
          __path__: /var/log/*.log
          
  - job_name: userservice
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: userservice
          __path__: /var/log/userservice/*.log

  - job_name: apigateway
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: apigateway
          __path__: /var/log/apigateway/*.log


