apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: NodePort
  selector:
    app: authservice
  ports:
  - name: http
    protocol: TCP
    port: 8084
    targetPort: 8084
    nodePort: 30084 # Optional: Specify a custom NodePort
  - name: grpc
    protocol: TCP
    port: 8085
    targetPort: 8085
    nodePort: 30085 # Optional: Specify a custom NodePort