apiVersion: v1
kind: Service
metadata:
  name: dlsmandatoryproject
spec:
  type: NodePort
  selector:
      app: dlsmandatoryproject
  ports:
  - name: http
    protocol: TCP
    port: 8081       # External port for HTTP
    targetPort: 8080 # Internal container port (application listening port)
    # range between 30000-32767
    nodePort: 30001 # NodePort for external access