apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: NodePort
  selector:
    app: authservice
  ports:
  - name: http
    protocol: TCP
    port: 8084       # External port for HTTP
    targetPort: 8080 # Internal container port (application listening port)
    nodePort: 30084  # Optional: Specify a custom NodePort



  # The nodePort is used to expose the service on a specific port on the Kubernetes node. If you don’t need direct node access, you can omit the nodePort and rely on port and targetPort.