apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: ClusterIP # Changed from NodePort to ClusterIP
  selector:
    app: authservice
  ports:
  - name: http
    protocol: TCP
    port: 8084 # External port for HTTP
    targetPort: 8080 # Internal container port (application listening port)



  # The nodePort is used to expose the service on a specific port on the Kubernetes node. If you don’t need direct node access, you can omit the nodePort and rely on port and targetPort.