name: User Service Microservice - Build, Test, Push image to Docker Hub

on:
  push:
    branches:
      - Shero
    paths:
      - "UserService/" # Trigger if files in UserService/ folder change
  workflow_dispatch: # Allows you to manually run the workflow from the Actions tab
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: false
      docker_password:
        description: 'Docker Hub Password'
        required: false

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # eller 7.0.x, afhængigt af din løsning

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test UnitTest --no-build --verbosity normal

  build-and-push:
    name: Build and Push Docker Image
    needs: test # Ensure the test job is completed before this job starts
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username || secrets.DOCKER_USERNAME }} # Store your Docker Hub username in GitHub Secrets
          password: ${{ github.event.inputs.docker_password || secrets.DOCKER_PASSWORD }} # Store your Docker Hub password/token in GitHub Secrets

      # Build and push Docker image for UserService microservice
      - name: Build and push Docker image for UserService microservice
        run: |
          docker build -t rashox/userservice:latest ./UserService
          docker push rashox/userservice:latest
 
