name: User Service Microservice - Build, Test, Push image to Docker Hub

on:
  push:
    branches:
      - Shero
    paths:
      - "UserService/**" # Trigger if files in UserService/ folder change
  workflow_dispatch: # Allows you to manually run the workflow from the Actions tab
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: false
      docker_password:
        description: 'Docker Hub Password'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username || secrets.DOCKER_USERNAME }} # Store your Docker Hub username in GitHub Secrets
          password: ${{ github.event.inputs.docker_password || secrets.DOCKER_PASSWORD }} # Store your Docker Hub password/token in GitHub Secrets

      # Run unit tests for UserService microservice
      - name: Run unit tests for UserService microservice
        run: |
          pushd ../../UnitTest
          docker run --rm -v ${{ github.workspace }}:/app -w /app mcr.microsoft.com/dotnet/sdk:6.0 dotnet test UserService.Tests/UserService.Tests.csproj --no-restore --verbosity normal
          popd

      # Build and push Docker image for UserService microservice
      - name: Build and push Docker image for UserService microservice
        run: |
          pushd ../../UserService
          docker build -t rashox/userservice:latest ./UserService
          docker push rashox/userservice:latest
          popd
 
